#!/usr/bin/env ruby

# Passenger agent to monitor status and memory status of passenger servers

require "rubygems"
require "bundler/setup"
require "newrelic_plugin"
require File.join(File.dirname(__FILE__), 'lib/status_parser')

module PassengerAgent

  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid "com.petalmd.passenger"
    agent_version "1.0.0"
    agent_config_options :passenger_status
    # Name of instance that will display in New Relic
    agent_human_labels("Passenger") { "#{`hostname`}" }

# Send stats to New Relic
    def poll_cycle

      #initialize
      @status = Status.new(run_command(passenger_status))

      # Report data from passegner-status command
      report_metric "passenger/processes/max", "Processes", @status.processes_max
      report_metric "passenger/processes/running", "Processes", @status.processes_current

      report_metric "passenger/requests/waiting", "Requests", @status.request_queue_size
      report_metric "passenger/requests/total", "Requests", @status.requests_total
      @status.requests_per_process.each do |pid, requests|
        report_metric "passenger/requests/detail/#{app}", "Requests", requests
      end

      report_metric "passenger/cpu/total", "CPU%", @status.cpu_total
      @status.cpu_per_process.each do |pid, cpu_usage|
        report_metric "passenger/cpu/detail/#{pid}", "CPU%", cpu_usage
      end

      report_metric "passenger/memory/total", "MB", @status.memory_total
      @status.memory_per_process.each do |pid, memory_usage|
        report_metric "passenger/memory/detail/#{pid}", "MB", memory_usage
      end

      @status.last_used_time_per_process.each do |pid, time_elapsed|
        report_metric "passenger/processes/time_since_last_used/#{pid}", "s", time_elapsed
      end

      @status.uptime_per_process.each do |pid, uptime|
        report_metric "passenger/processes/uptime/#{pid}", "s", uptime
      end
    end

    private

# Run command on passenger server to get data
    def run_command(command)

      result = `#{command}`
      unless $?.success?
        $stderr.puts "command: #{command} failed"
        exit 1
      end
      result
    end

  # Register this agent with the component.
  NewRelic::Plugin::Setup.install_agent :passenger, PassengerAgent

  # Launch the agent; this never returns.
  NewRelic::Plugin::Run.setup_and_run
  end

end
